version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__DatabaseName=DraftEngine
    depends_on:
      - mongo

  frontend:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile.prod
    volumes:
      - frontend_build:/app/dist

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    expose:
      - "27017"

volumes:
  mongodb_data:
  frontend_build:
