version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5246:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__DatabaseName=DraftEngine
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    depends_on:
      - mongo

  frontend:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5246
    volumes:
      - ./ClientApp:/app
      - /app/node_modules
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
