FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN yarn install

# Expose the port Vite runs on
EXPOSE 5173

# Start Vite development server
CMD ["yarn", "dev", "--host", "0.0.0.0"]
